-- Müşteri görüşleri seed (8 kayıt)
INSERT INTO testimonials (client_name, client_title, client_company, testimonial_text, rating, display_order, is_featured, is_active)
SELECT * FROM (
  VALUES
    ('Selin Acar', 'Kurucu', 'Çağla Şeker Beauty', 'Genua ile çalışmaya başladığımızda sosyal medyada tutarlı bir dilimiz yoktu. Üç aylık içerik planı, Reels çekimleri ve kampanya kurgusu sonrası hem etkileşim hem de randevu taleplerimiz belirgin şekilde arttı. En çok raporları her ay anlaşılır sunmalarını sevdik.', 5, 1, TRUE, TRUE),
    ('Kerem Yıldız', 'Operasyon Direktörü', 'Kaburgacı Usta', 'Restoran zinciri olarak dijitalde görünürlüğümüz sınırlıydı. Genua ekibi lokasyon bazlı Meta reklamları ve açılış dönemi kreatifleriyle yeni şubelerimizde ciddi talep yarattı. Hızlı iletişim ve sahaya yakın ekip anlayışı fark yarattı.', 5, 2, FALSE, TRUE),
    ('Aylin Tosun', 'Denizli Bölge Müdürü', 'Simya Sigorta', 'Sigorta sektöründe dijitalden gelen lead kalitesi her zaman kritik. Genua, landing page yapımızdan reklam metinlerine kadar süreci uçtan uca kurguladı. Beş ayda form başına maliyetimiz düştü, satış ekibimize giden başvurular daha nitelikli hale geldi.', 5, 3, TRUE, TRUE),
    ('Burak Demir', 'Pazarlama Müdürü', 'Alfin Yapı', 'Konut projelerimizin lansman dönemlerinde Google ve sosyal medyada aynı mesajı taşımak zordu. Genua ile marka dili, görsel sistem ve performans reklamlarını tek çatı altında topladık. Proje öncesi talep toplama kampanyalarında ölçülebilir sonuç aldık.', 5, 4, FALSE, TRUE),
    ('Defne Gürel', 'E-Ticaret Sorumlusu', 'Mazzini Mobilya', 'Ürün fotoğrafından katalog çekimlerine, Instagram vitrininden indirim dönemi reklamlarına kadar tüm içerik ihtiyacımızı karşıladılar. Ajans değil, içimizden biri gibi çalışıyorlar; bu da e-ticaret hedeflerimizi daha net yönetmemizi sağladı.', 5, 5, FALSE, TRUE),
    ('Onur Çelik', 'Kurucu Ortak', 'Hiera Coffee', 'Kafe markası olarak estetik ve mesaj tutarlılığı bizim için her şey. Genua, marka kimliğimizi dijital kanallara taşırken hiç ajans şablonu hissettirmedi. Story formatlarından mekân içi çekimlere kadar tüm üretim hızlı ve kaliteli ilerledi.', 5, 6, FALSE, TRUE),
    ('Zeynep Korkmaz', 'İşletme Müdürü', 'Meftune Restoran', 'Sezonluk menü duyuruları ve rezervasyon odaklı kampanyalar için kısa sürede çözüm üretmeleri işimize yaradı. Grafikten video kurgusuna kadar tek elden yönetim, operasyon yoğunken bize ciddi zaman kazandırdı.', 5, 7, FALSE, TRUE),
    ('Cem Aydın', 'İş Geliştirme Direktörü', 'Engiz İnşaat', 'Kurumsal inşaat firması olarak itibar yönetimi ve profesyonel görünüm önceliğimizdi. Web sitesi yenileme, kurumsal sunum setleri ve LinkedIn odaklı görünürlük çalışmasıyla müteahhit profilimizi güçlendirdik. Kamu ve kurumsal projelerdeki tecrübeleri bizi rahatlattı.', 5, 8, TRUE, TRUE)
) AS seed(client_name, client_title, client_company, testimonial_text, rating, display_order, is_featured, is_active)
WHERE NOT EXISTS (SELECT 1 FROM testimonials LIMIT 1);
